### ISSUE TITLE
Consistent, App Specific, Error... 

### ISSUE THREAD

**Issue by Ibuprophen** [heagoo/apk_builder_tutorial#4]
Hello There! :-)

I had just emailed the following to you and then I had realized that you were on Github as well. 

I'm having an issue that's in no way linked to the app I'm building but, specific to the APK Builder App.

The following is consistent with a few different ones I'm building...

Failed to generate resource table for split ''
/storage/emulated/0/ApkBuilder/.maven-cache/appcompat-v7-28.0.0/res/values-v28/values-v28.xml:7: error: Error: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').

I can't think of why this one and only issue is happening.

Also, the APK Builder App is up to date.

Thank you very much for your time and understanding with this.

**Comment by heagoo** [comment]
I guess the android.jar inside APK Builder is a little old.
How about change 28.0.0 to some older version like 27.1.1 inside build.gradle? (may need to restart APK Builder after modification)

**Comment by Ibuprophen** [comment]
I'm going to give the older version idea a try and a few other ideas. 

Regarding the restarting of the Builder App, I've already tried that idea. 

I'll get back to you soon with my findings @heagoo... 👍 


~Ibuprophen

**Comment by Ibuprophen** [comment]
I'm going to close this topic as a disinterested topic from the developer... 


~Ibuprophen
